---
- name: add apt repositories
  become_user: root
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present

- name: install packages
  become_user: root
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - exuberant-ctags
    - neovim

- name:  create configuration directory
  become_user: "{{vim_username}}"
  file:
    path: /home/{{vim_username}}/.config/nvim
    state: directory

- name: link dotfiles
  become_user: "{{vim_username}}"
  file:
    dest: /home/{{vim_username}}/{{item.dest}}
    src: /home/{{vim_username}}/.cloned-repos/dotfiles/{{item.src}}
    state: link
  with_items:
    - { src: "vim/.vimrc", dest: ".vimrc" }
    - { src: "vim/.vimrc", dest: ".config/nvim/init.vim" }

- name: link Neovim configuration directory
  become_user: "{{vim_username}}"
  file:
    dest: /home/{{vim_username}}/.vim
    src: /home/{{vim_username}}/.config/nvim
    state: link

- name: install Vundle
  become_user: "{{vim_username}}"
  git:
    dest: /home/{{vim_username}}/.vim/bundle/Vundle.vim
    repo: https://github.com/VundleVim/Vundle.vim.git

- name: install Vundle plugins
  become_user: "{{vim_username}}"
  shell: HOME=/home/{{vim_username}} vim -c VundleUpdate -c quitall > /dev/null

- name: update alternatives
  become_user: root
  alternatives:
    name: "{{item.name}}"
    path: "{{item.path}}"
  with_items:
    - { name: "editor", path: "/usr/bin/nvim" }
    - { name: "vi", path: "/usr/bin/nvim" }
    - { name: "vim", path: "/usr/bin/nvim" }