---
- name: install package
  become_user: root
  unarchive:
    dest: /usr/local/bin
    remote_src: yes
    src: https://releases.hashicorp.com/packer/{{packer_version}}/packer_{{packer_version}}_linux_amd64.zip