---
- name: install package
  become_user: root
  apt:
    deb: https://github.com/justwatchcom/gopass/releases/download/v{{gopass_version}}/gopass-{{gopass_version}}-linux-amd64.deb

- name: create link from gopass to pass
  become_user: root
  file:
    dest: /usr/local/bin/pass
    force: yes
    src: /usr/local/bin/gopass
    state: link

- name: add configuration directory
  become_user: "{{gopass_username}}"
  file:
    group: "{{gopass_username}}"
    owner: "{{gopass_username}}"
    path: /home/{{gopass_username}}/.config/gopass
    recurse: yes
    state: directory

- name: create configuration file
  become_user: "{{gopass_username}}"
  template:
    dest: /home/{{gopass_username}}/.config/gopass/config.yml
    group: "{{gopass_username}}"
    owner: "{{gopass_username}}"
    src: ../templates/config.yml.j2

- name: create SSH configuration directory
  file:
    dest: /home/{{gopass_username}}/.ssh
    state: directory

- name: add AWS CodeCommit configuration
  become_user: "{{gopass_username}}"
  blockinfile:
    block: |
      Host git-codecommit.*.amazonaws.com
        User {{gopass_ssh_key_id}}
    create: yes
    dest: /home/{{gopass_username}}/.ssh/config

