---
- name: install package
  become_user: root
  apt:
    name: openjdk-{{java_version}}-jdk
    state: present

- name: install Maven
  become_user: root
  apt:
    name: maven
    state: present

- name: update Zsh configuration
  become_user: "{{java_username}}"
  lineinfile:
    create: yes
    dest: /home/{{java_username}}/.zshrc-extra
    line: "export JAVA_HOME=/usr/lib/jvm/java-{{java_version}}-openjdk-amd64"
    regexp: "^export JAVA_HOME"
    state: present
