---
- name: set configuration
  become_user: "{{git_username}}"
  git_config:
    name: "{{item.name}}"
    scope: global
    value: "{{item.value}}"
  with_items:
    - { name: "user.email", value: "{{git_email}}" }
    - { name: "user.name", value: "{{git_name}}" }